### PR TITLE
Add "Two year radar" notes

### PR DESCRIPTION
**Pull request by betatim**
Add notes from the discussion on the "two year radar" at the 2023 sprint in Paris.

### CODE REVIEW

**Comment by jjerphan** [comment]
Thanks for writing those notes! Some items looks promising! Can people who were not at the meeting add a few comments or votes?

**Comment by betatim** [comment]
The votes were used to help figure out what to talk about, so I think voting now isn't useful?

Comments on topics would be useful though. I wonder what the best way to this is. Should we make PRs to this PR? Merge this PR and then make a new PR with your comments? What do you think?

**Comment by jjerphan** [comment]
Would it make sense to convert items to "epics" or to GitHub discussions?

**Comment by betatim** [comment]
For now I'd not create issues. If we do spring into action on one of the topics or want to discuss them further then we should, but not if there isn't someone who desires a discussion/action.

**Pull request merged**
